services:
  app:
    image: tr23malyarchuk/ecolog:v1.1
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Av_s0l*YaM4)2005
      MYSQL_DATABASE: ecolog
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
